spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/foodshop
    username : sa
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug



